// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtz61YAGlZZBTBOmNDaCPhkoFuj-D_2U',
    appId: '1:953105876974:web:99f259f4c9bf4765d8f0ff',
    messagingSenderId: '953105876974',
    projectId: 'riverpod-clean',
    authDomain: 'riverpod-clean.firebaseapp.com',
    storageBucket: 'riverpod-clean.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTrLGIavjvgLFEQdNlA9LPBnjxodR47U',
    appId: '1:953105876974:android:9c0ebed8bcf0223ad8f0ff',
    messagingSenderId: '953105876974',
    projectId: 'riverpod-clean',
    storageBucket: 'riverpod-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKEmOpv5HX68aQ_ayFWLMgSWyAEjedlk',
    appId: '1:953105876974:ios:5859ac2e6aef3e8ad8f0ff',
    messagingSenderId: '953105876974',
    projectId: 'riverpod-clean',
    storageBucket: 'riverpod-clean.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKEmOpv5HX68aQ_ayFWLMgSWyAEjedlk',
    appId: '1:953105876974:ios:5859ac2e6aef3e8ad8f0ff',
    messagingSenderId: '953105876974',
    projectId: 'riverpod-clean',
    storageBucket: 'riverpod-clean.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtz61YAGlZZBTBOmNDaCPhkoFuj-D_2U',
    appId: '1:953105876974:web:a51b5f797bda7741d8f0ff',
    messagingSenderId: '953105876974',
    projectId: 'riverpod-clean',
    authDomain: 'riverpod-clean.firebaseapp.com',
    storageBucket: 'riverpod-clean.firebasestorage.app',
  );
}
